### ISSUE TITLE
Add new resource type: Store

### ISSUE THREAD

**Issue by shenjiangqiu** [garro95/desim#13]
pull request: #12
1. motivation:
  the Store in simpy has a feature: the sender can wait on the store when the store is full and the receiver can wait on the store when the store is empty. So the scheduler needs to be changed when encountering Request and Release events
- current behavior: when Request happened: the scheduler will issue one new event when the resource return Some event or zero when the resource returns None when Release happened: the scheduler will issue 2 events when the resource return Some event and issue 1 event(the original one) when the resource returns nothing.
- new behavior: 
  - when requesting on a store: the scheduler will need to schedule zero, one, or two events depending on the current store  ( #12 ), as same as when releasing on a store
 
2. things change from the original code:
 -  change the Resource trait return type:
```rust
pub trait Resource<T> {
    fn allocate_or_enqueue(&mut self, event: Event<T>) -> Vec<Event<T>>;
    fn release_and_schedule_next(&mut self, event: Event<T>) -> Vec<Event<T>>;
}
```
instead of returning an optional value, the resource can now return zero or multiple events
 - change the scheduler behavior:
```rust
                            Effect::Request(r) => {
                                let res = &mut self.resources[r];
                                let request_event = Event::new(self.time, event.process(), y);
                                for e in res.allocate_or_enqueue(request_event) {
                                    self.future_events.push(Reverse(e))
                                }
                            }
                            Effect::Release(r) => {
                                let res = &mut self.resources[r];
                                let request_event = Event::new(self.time, event.process(), y);
                                let events = res.release_and_schedule_next(request_event);
                                for e in events {
                                    self.future_events.push(Reverse(e));
                                }
                            }
```
now the scheduler always schedules all the events that the resource returned.
  - chagne the original SimpleResource implementation: release will always return at least one event.
```rust
    fn release_and_schedule_next(&mut self, event: Event<T>) -> Vec<Event<T>> {
        match self.queue.pop_front() {
            Some(mut request_event) => {
                // some is waiting for the request, schedule it! and schedule the self
                request_event.set_time(event.time());
                vec![request_event, event]
            }
            None => {
                // no one is waiting for the resorce, restore the availiable and return self
                assert!(self.available < self.quantity);
                self.available += 1;
                vec![event]
            }
        }
    }
```

3. new store type: see #12

**Comment by garro95** [comment]
The feature looks very interesting. I am thinking that maybe it should be another Trait though?
Even if the operations are very similar, they have a different nature and it could be hard for an implementer to understand how to implement the trait for a resource of this type.

**Comment by shenjiangqiu** [comment]
Sounds reasonable! A Resouce trait is not good enough to describe a store type, I'll try to make some new changes.
