### ISSUE TITLE
Unresolved imports in v0.2

### ISSUE THREAD

**Issue by cndolo** [garro95/desim#16]
Hi,

Using `desim v0.2` results in some import errors in the examples or when using `desim`  as described in the examples.
For example,  the carwash example does not compile with the following errors:

```
18 | use desim::prelude::*;
   |            ^^^^^^^ could not find `prelude` in `desim`

error[E0432]: unresolved import `desim::resources`
  --> simulator/src/bin/carwash.rs:19:12
   |
19 | use desim::resources::SimpleResource;
   |            ^^^^^^^^^ could not find `resources` in `desim`
```

In contrast, the example compiles successfully using the version on git , i.e. `desim = {git = "https://github.com/garro95/desim"}` .
The crate has not been updated on crates.io which is evident when looking at the last update on crates.io vs the commit history here. 
It would be nice if you would update the crate.

**Comment by garro95** [comment]
That is because that features were introduced in 0.3.0 that I did not publish. I don't remember if there was a reason for that or not, but it's published on crates.io now
